language: node_js

node_js:
  - 'stable'
  - '4.4'

services: mongodb

env:
  global:
    - TWILIO_ACCOUNT_SID=AC2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_NUMBER=+15551230987
    - MONGO_URL_TEST=mongodb://localhost/appointment-reminders-node-test
    - MONGO_URL=mongodb://localhost/appointment-reminders-node-test

cache:
  directories:
    - node_modules
